categories = ["image", "video"]
css = [
	"css/w3pro.css",
	"css/base.css",
	"css/filetree.css",
]
scripts = [ 
	"js/filetree.js",
]

[category.swiper]
css = [
	"swiper/swiper-bundle.min.css",
	"swiper/swiper.css",
	"swiper/gallery.css",
]
scripts = [
	"swiper/swiper-bundle.min.js",
]
[category.swiper.video]
	muted = true
	autoplay = false
	controls = true
	loop = false

[color]
bg = "#262626"
fg = "#ffbf00"
white = "#ffffff"
black = "#262626"
grey = "#626262"
yellow = "#ffff87"
red = "#ff5f5f"
pink = "#ffafff"
cyan = "#afffff"
blue = "#5fafff"
green = "#afffaf"
purple = "#af87ff"


