categories = ["image", "video"]
css = [
	"static/w3/w3pro.css",
]
scripts = [ ]

[collection.image]
mime = "image"
css = [
	"static/swiper/swiper-bundle.min.css",
	"static/swiper/swiper.css",
	"static/swiper/gallery.css",
]
scripts = [
	"static/swiper/swiper-bundle.min.js",
]

[collection.video]
mime = "video"
css = [
	"static/swiper/swiper-bundle.min.css",
	"static/swiper/swiper.css",
	"static/swiper/gallery.css",
]
scripts = [
	"static/swiper/swiper-bundle.min.js",
]
[collection.video.html.video]
	muted = true
	autoplay = false
	controls = true

[color]
bg = "#262626"
fg = "#ffbf00"
white = "#ffffff"
black = "#262626"
grey = "#626262"
yellow = "#ffff87"
red = "#ff5f5f"
pink = "#ffafff"
cyan = "#afffff"
blue = "#5fafff"
green = "#afffaf"
purple = "#af87ff"


